### ISSUE TITLE
Fix CI

### ISSUE THREAD

**Issue by matevz** [oasisprotocol/web3-tests#2]
Currently all e2e tests are correctly executed locally, but CI fails with some CI-specific issues. 

- [ ] e2e_browsers:

```
15 10 2021 13:10:46.461:INFO [Chrome Headless 94.0.4606.81 (Linux x86_64)]: Connected on socket ytsc98M-UxKKSiiJAAAB with id 48484375

  window.Web3 is defined
    ✗ loads
	Error: "window.Web3" was not defined
	    at Context.<anonymous> (test/e2e.minified.js:9:29)


Chrome Headless 94.0.4606.81 (Linux x86_64): Executed 1 of 1 (1 FAILED) (0.002 secs / 0 secs)
TOTAL: 1 FAILED, 0 SUCCESS


1) loads
     window.Web3 is defined
     Error: "window.Web3" was not defined
    at Context.<anonymous> (test/e2e.minified.js:9:29)
```

- [ ] e2e_ganache:

```
Error: Cannot find module './lib/confirmGasPrice'
Require stack:
- /home/runner/work/web3-tests/web3-tests/test/ganache-core/test/local/gas/gas.js
- /home/runner/work/web3-tests/web3-tests/test/ganache-core/node_modules/mocha/lib/esm-utils.js
- /home/runner/work/web3-tests/web3-tests/test/ganache-core/node_modules/mocha/lib/mocha.js
- /home/runner/work/web3-tests/web3-tests/test/ganache-core/node_modules/mocha/lib/cli/one-and-dones.js
- /home/runner/work/web3-tests/web3-tests/test/ganache-core/node_modules/mocha/lib/cli/options.js
- /home/runner/work/web3-tests/web3-tests/test/ganache-core/node_modules/mocha/bin/mocha
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (/home/runner/work/web3-tests/web3-tests/test/ganache-core/test/local/gas/gas.js:4:25)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at requireOrImport (/home/runner/work/web3-tests/web3-tests/test/ganache-core/node_modules/mocha/lib/esm-utils.js:15:12)
    at Object.exports.loadFilesAsync (/home/runner/work/web3-tests/web3-tests/test/ganache-core/node_modules/mocha/lib/esm-utils.js:28:26)
    at singleRun (/home/runner/work/web3-tests/web3-tests/test/ganache-core/node_modules/mocha/lib/cli/run-helpers.js:149:3)
    at exports.runMocha (/home/runner/work/web3-tests/web3-tests/test/ganache-core/node_modules/mocha/lib/cli/run-helpers.js:186:5)
    at Object.exports.handler (/home/runner/work/web3-tests/web3-tests/test/ganache-core/node_modules/mocha/lib/cli/run.js:319:5)
```

- [ ] e2e_mosaic:

```
Error: Cannot read file /home/runner/work/web3-tests/web3-tests/test/mosaic-1/artifacts/Anchor.json.Truffle compile must be run before building the package.That should be done automatically when running `npm publish`.
    at /home/runner/work/web3-tests/web3-tests/test/mosaic-1/tools/build_package.js:51:11
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/home/runner/work/web3-tests/web3-tests/test/mosaic-1/tools/build_package.js:44:15)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47
```

**Comment by matevz** [comment]
I temporarily disabled tests in 9e0a5e5ec11e7b0bc4b5d61509b3d393712ac418 to make PRs mergable.
